config/routes.rb
Uklocumdoctors::Application.routes.draw do

  devise_for :users

   namespace :admin do
     root :to => 'doctors#index'
     resources :staffs
     resources :doctors 
     resources :users
   end

  resources :doctors
  resources :nurse_practitioners
  resources :users do
    resources :locations
    resources :schedules do
      collection do
        get 'get_schedules'
      end
    end
  end

   root :to => 'dashboard#index'
  
  get "settingstandards" => "dashboard#settingstandards"
  get "generalpractitioners" => "dashboard#generalpractitioners"
  get "doctorinfo" => "dashboard#doctorinfo"
  get "nursesinfo" => "dashboard#nursesinfo"
  get "aboutus" => "dashboard#aboutus"
  match "contactus" => "dashboard#contactus" , via: [:post, :get]
  get "register" => "dashboard#register"
  get "contactonline" => "dashboard#contactonline"

  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/admin/doctors_controller.rb
class Admin::DoctorsController < Admin::BaseController


  def index
  	@search = User.doctors.includes([:profile]).search(params[:search])
    @doctors = @search.paginate(:page => params[:page], :per_page => 10)
  end


  def new
  	@doctor = User.new()
  	@doctor.build_profile
  end

  def create
  	@doctor = User.new(params[:user])
  	if @doctor.save
  	  @doctor.roles << Role.find_by_name("doctor")
  	end
  end

  def edit
  	@doctor = User.find(params[:id])
  end


  def show
    @doctor = User.find(params[:id])
  end

  def update
  	@doctor = User.find(params[:id])
    remove_password_from_params_if_blank  	
  	@doctor.update_attributes(params[:user])
  end

  def destroy
    @doctor = User.find(params[:id])
    @doctor.destroy
    redirect_to admin_doctors_path
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def new
  	@doctor = User.new
  	@doctor.build_profile
  end


  def create
  	@doctor = User.new(params[:user])
  	if @doctor.save
  	  @doctor.roles << Role.find_by_name("doctor")
      Resque.enqueue(UserRegister, 'doctor',  @doctor.id.to_s,  @doctor.name)
  	  sign_in @doctor 
  	end
  end

  def edit
    @doctor = current_user
  end

  def update
    @doctor = current_user
    remove_password_from_params_if_blank    
    if @doctor.update_attributes(params[:user])
      Resque.enqueue(UserProfileUpdated, 'doctor',  @doctor.id.to_s,  @doctor.name)
    end
  end  
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/admin/doctors/_edit_form.html.haml
= simple_form_for(@doctor, :url => admin_doctor_path(@doctor),  :remote => true) do |f|
  = render "fields", {:f => f}
  = f.button :submit, "Update Doctor", :class => 'save-btn ', :disable_with => 'Saving...'

app/views/admin/doctors/_fields.html.haml
.clearfix
  .left.gap_right= f.input :name
  .left.gap_right= f.input :email
  .left= f.input :username
.clearfix
  .left.gap_right= f.input :password
  .left= f.input :password_confirmation

.left
  = f.fields_for :profile do |pro|
    .left.gap_right= pro.input :organisation
    .left.gap_right= pro.input :telephone_day, :label => "Telephone (Day)"
    .left= pro.input :telephone_night, :label => "Telephone (Night)"
    .clear
    .left.gap_right= pro.input :mobile
    .left= pro.input :fax
    .clear
    .left.gap_right= pro.input :speciality
    .left= pro.input :qualification
    .clear
    .left.gap_right= pro.input :address,  :input_html => { :class => 'description' }
    .left= pro.input :other_information,  :input_html => { :class => 'description' }
    .clear

.clear

app/views/admin/doctors/_form.html.haml
= simple_form_for(@doctor, :url => admin_doctors_path,  :remote => true) do |f|
  = render "fields", { :f => f }
  = f.button :submit, "Create Doctor", :class => 'save-btn', :disable_with => 'Saving...'

app/views/admin/doctors/create.js.erb
<% if @doctor.errors.blank? %>
   window.location.href = window.location.href;  
<%else%>
  $('#doctor').html("<%= escape_javascript(render :partial => '/admin/doctors/form' )%>");
<%end%>

app/views/admin/doctors/edit.js.erb
$('#doctor').html("<%= escape_javascript(render :partial => '/admin/doctors/edit_form' )%>").dialog({ zIndex: 3000, width: "70%", title: "Edit - <%= @doctor.name %>", modal: true , resizable: false});
 

app/views/admin/doctors/index.html.haml
%ul.breadcrumb
  %li.title 
    Listing doctors
  %li.active.right Doctors  
  %li.right
    Admin
    = divider

= form_for(@search, :url => admin_doctors_path, :html => { :class => 'form-search' }) do |f|
  %table.table.table-bordered.search_table 
    %tbody
      %tr
        %td= f.text_field :name_contains, :placeholder => "Name contains"
        %td= f.text_field :profile_mobile_contains, :placeholder => "Mobile"
        %td
          = icon_button("Search", 'icon-search', 'btn')
          .right= link_to new_text('Doctor'), new_admin_doctor_path, :remote => true , :class => 'btn btn-success'
 
%table.table.table-bordered
  %thead
    %tr
      %th Name
      %th Username
      %th mobile
      %th Address
      %th
 
  %tbody
    - @doctors.each do |doctor|
      %tr 
        %td= doctor.name
        %td= doctor.username
        %td= doctor.profile.mobile
        %td= doctor.profile.address
        %td.width27per
          = link_to "Details", admin_doctor_path(doctor), :class => 'btn btn-mini'
          = link_to edit_text(), edit_admin_doctor_path(doctor), :class => 'btn btn-mini', :remote => true  
          = link_to "Schedules", user_schedules_path(doctor), :class => 'btn btn-info btn-mini'
          = link_to "Locations", user_locations_path(doctor), :class => 'btn btn-info btn-mini'
          = link_to "Delete", admin_doctor_path(doctor), :method => :delete, :confirm => "Are you sure? ", :class => 'btn btn-danger btn-mini'



= will_paginate(@doctors)

#doctor

app/views/admin/doctors/new.js.erb
$('#doctor').html("<%= escape_javascript(render :partial => '/admin/doctors/form' )%>").dialog({ zIndex: 3000, width: "70%", title: 'New Doctor', modal: true, resizable: false });

app/views/admin/doctors/show.html.haml
%ul.breadcrumb
  %li.title 
    = @doctor.name
  %li.active.right= @doctor.name  
  %li.right
    Doctors
    = divider   
  %li.right
    Admin
    = divider

.pull-left
  %h2 Details
.pull-right
  = link_to edit_text(), edit_admin_doctor_path(@doctor), :class => 'btn btn-info', :remote => true  
  = link_to "Doctor Lists", admin_doctors_path, :class => 'btn'

.clearfix    

%table.table.table-bordered
  
  %tr
    %th Name
    %td= @doctor.name
  %tr
    %th Email
    %td= @doctor.email
  %tr
    %th UserName
    %td= @doctor.username
  %tr
    %th speciality
    %td=@doctor.profile.speciality rescue ""
  %tr
    %th qualification
    %td=@doctor.profile.qualification rescue ""
  %tr
    %th Organisation
    %td=@doctor.profile.organisation rescue ""
  %tr
    %th Telephone day 
    %td=@doctor.profile.telephone_day  rescue ""
  %tr
    %th Telephone night
    %td= @doctor.profile.telephone_night  rescue ""
  %tr
    %th Mobile
    %td= @doctor.profile.mobile rescue ""
  %tr
    %th Fax
    %td=@doctor.profile.fax rescue ""

  %tr
    %th Address
    %td=@doctor.profile.address rescue ""
  %tr
    %th Other information
    %td=@doctor.profile.other_information  rescue ""

#doctor

app/views/admin/doctors/update.js.erb
<% if @doctor.errors.blank? %>
   window.location.href = window.location.href;  
<%else%>
  $('#doctor').html("<%= escape_javascript(render :partial => '/admin/doctors/edit_form' )%>");

<%end%>