config/routes.rb
Uklocumdoctors::Application.routes.draw do

  devise_for :users

   namespace :admin do
     root :to => 'doctors#index'
     resources :staffs
     resources :doctors 
     resources :users
   end

  resources :doctors
  resources :nurse_practitioners
  resources :users do
    resources :locations
    resources :schedules do
      collection do
        get 'get_schedules'
      end
    end
  end

   root :to => 'dashboard#index'
  
  get "settingstandards" => "dashboard#settingstandards"
  get "generalpractitioners" => "dashboard#generalpractitioners"
  get "doctorinfo" => "dashboard#doctorinfo"
  get "nursesinfo" => "dashboard#nursesinfo"
  get "aboutus" => "dashboard#aboutus"
  match "contactus" => "dashboard#contactus" , via: [:post, :get]
  get "register" => "dashboard#register"
  get "contactonline" => "dashboard#contactonline"

  # match ':controller(/:action(/:id))(.:format)'
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :created_by, :location_id, :schedule_start, :notes, :schedule_end, :practitioner_id


  belongs_to :practitioner, :class_name => "User", :foreign_key => "practitioner_id"
  belongs_to :created_by, :class_name => "User", :foreign_key => "creator_id"
  belongs_to :location

  validates :notes, :schedule_start, :schedule_end,  :presence => true

  scope :order_start_asc, -> { order("schedule_start ASC") }
  scope :this_week,  -> {where("schedule_start >= '#{Date.today}'").where("schedule_end <= '#{Date.today + 7}'")}
  delegate :name, :to => :location, :prefix => true, :allow_nil => true

  def self.get_schedules(from, to)
    from_date = from.to_date
    to_date = to.to_date
    self.where("schedule_start >= '#{from_date}'").where("schedule_end <= '#{to_date}'")
  end

  def to_fullcalender
    attribute_hash = {:id => "schedule-#{self.id.to_s}", :title => self.full_description_for_calender, :description => self.full_description_for_calender, :start => schedule_start.iso8601, :end => schedule_end.iso8601, :allDay => 0  }
  end

  def full_description_for_calender
    string = ""
    string += "location: #{self.location_name rescue ''} ," unless  location_id.blank?
    string += "#{self.notes.to_s}"
    return string
  end


  def schedule_from_to
    "#{schedule_start.strftime("%Y-%m-%d %H:%M")} - #{schedule_end.strftime("%Y-%m-%d %H:%M")}"
  end

  def schedule_start_time
    "#{schedule_start.strftime("%d-%m-%Y %H:%M:%S")}"
  end

  def schedule_time
    schedule_start.to_date.strftime("%d/%m/%Y").to_s
  end

  def schedule_end_time
    "#{schedule_end.strftime("%d-%m-%Y %H:%M:%S")}"
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < PractitionerBaseController

  layout 'appointment'
 
  before_filter :authenticate_user!
  before_filter :find_user
  before_filter :check_user_is_practitioner

  def index
    @locations = @user.locations
  end

  def new
    @schedule = Schedule.new({:schedule_start => params[:starttime] , :schedule_end =>  params[:endtime]})
    @locations = @user.locations
  end

  def create
    @schedule = Schedule.new(params[:schedule])

    @schedule.practitioner_id = @user.id
    @schedule.creator_id = current_user.id
    if @schedule.save
      Resque.enqueue(ScheduleAdded, current_user.user_role_type, current_user.id, current_user.name, (@schedule.location.name rescue ''), @schedule.schedule_time, @schedule.notes) #unless current_user.admin?
    else
      @locations = @user.locations
    end
  end


  def show
    @schedule = @user.schedules.find(params[:id])
  end


  def edit
    @schedule = @user.schedules.find(params[:id])
    @locations = @user.locations
  end

  def update
    @schedule = @user.schedules.find(params[:id])
    @schedule.attributes = params[:schedule]
    changes =  @schedule.changes

    if @schedule.save 
      #unless current_user.admin?
        Resque.enqueue(ScheduleChanged, current_user.user_role_type, current_user.id, current_user.name, (@schedule.location.name rescue ''), @schedule.schedule_time, @schedule.notes) unless changes.blank?
     # end
    end
  end  


  def destroy
    @schedule = @user.schedules.find(params[:id])
    @schedule.destroy
    Resque.enqueue(ScheduleDeleted, current_user.user_role_type, current_user.id, current_user.name, (@schedule.location.name rescue ''), @schedule.schedule_time, @schedule.notes)  #unless current_user.admin?
  end


  def get_schedules
    #from = (Time.at(params['start'].to_i) ).utc
    #to = Time.at(params['end'].to_i).utc

    @schedules = Schedule.includes([:location]).where("practitioner_id = ?", @user.id) #.get_schedules(from + 1.day, to + 7.day)
    @schedules = @schedules.where("location_id = ?", params[:location_id]) unless params[:location_id].blank?

 	  respond_to do |format|
      format.json {
            objects = []
            @schedules.each do |schedule|
              objects << schedule.to_fullcalender
            end
            objects.flatten!
            render :text => objects.to_json
         }
         format.js
    end
  end






end

app/helpers/admin/schedules_helper.rb
module Admin::SchedulesHelper
end

app/views/schedules/_form.html.haml
= simple_form_for([@user, @schedule], :remote => true) do |f|

  = f.input :notes, :input_html =>  { :class => "input-xxlarge", :rows => 2}
  .pull-left.gap_right= f.input :location_id, :as => :select, :collection => @locations
  .pull-left.margin-top-30= link_to "<i>+ add new Location<i>".html_safe, new_user_location_path(@user, :from => "schedule"), :remote => true
  .clearfix
  %hr

  .pull-left.gap_right= f.input :schedule_start, :as => :string, :input_html => { :value => ( @schedule.schedule_start_time rescue nil)}
  .pull-left= f.input :schedule_end, :as => :string, :input_html => { :value => ( @schedule.schedule_end_time rescue nil)}
  .clearfix
  

  = f.submit "Schedule", :class => "save-btn"

app/views/schedules/_show.html.haml
- unless @schedule.location_id.blank?
  %p
    %b Location :
    = @schedule.location.name
%p
  %b Schedule :
  = @schedule.schedule_from_to

%p
  %b Notes :
  = @schedule.notes



- if current_user.admin? || @schedule.practitioner_id == current_user.id
  = link_to "Edit", edit_user_schedule_path(@user, @schedule.id), :class => 'btn', :remote => true
  = link_to "Delete", user_schedule_path(@user, @schedule.id), :method => :delete, :confirm => "Are you sure?", :class => 'btn btn-danger', :remote => true

app/views/schedules/create.js.erb
<% if @schedule.errors.blank? %>
  $("#new-object").dialog("destroy");
  var event = $.parseJSON("<%= escape_javascript @schedule.to_fullcalender.to_json.html_safe %>");
  $('#calendar').fullCalendar('renderEvent', event);
<%else%>
  $("#new-object").html("<%= escape_javascript(render :partial => '/schedules/form' )%>").dialog({ zIndex: 3000, width: "70%", title: 'New Schedule', modal: true, resizable: false });
  schedule_date_picker();
<%end%>

app/views/schedules/destroy.js.erb
$("#schedule_details").dialog('destroy');
 $('#calendar').fullCalendar( 'removeEvents', "schedule-<%= @schedule.id.to_s %>");

app/views/schedules/edit.js.erb
$("#new-object").html("<%= escape_javascript(render :partial => '/schedules/form' )%>").dialog({ zIndex: 3000, width: 600, title: 'New Schedule', modal: true, resizable: false });
schedule_date_picker();

app/views/schedules/index.html.haml
= hidden_field_tag("date_picked")

#calendar



#new-object
#new-location
#schedule_details


= content_for :extra_javascript do  
  %script
    var user_id = "#{@user.id}";
    displaycalender();
    $("#datepicker").datepicker({dateFormat: 'dd-mm-yy', changeMonth: true, changeYear: true, altFormat: "dd-mm-yy",altField: "#date_picked", onSelect: function(dateText, dp) { list_schedules();   } });

app/views/schedules/new.js.erb
$("#new-object").html("<%= escape_javascript(render :partial => '/schedules/form' )%>").dialog({ zIndex: 3000, width: 600, title: 'New Schedule', modal: true, resizable: false });
schedule_date_picker();


$("select#schedule_location_id").val($("select#locations").val());

app/views/schedules/show.js.erb
$("#schedule_details").html("<%= escape_javascript(render :partial => '/schedules/show' )%>").dialog({ zIndex: 3000, width: 600, title: 'Schedule Details', modal: true, resizable: false });

app/views/schedules/update.js.erb
<% if @schedule.errors.blank? %>
  $("#new-object").dialog("destroy");
  $("#schedule_details").html("<%= escape_javascript(render :partial => '/schedules/show' )%>").dialog({ zIndex: 3000, width: 600, title: 'Schedule Details', modal: true, resizable: false });


   var c = $("#calendar").fullCalendar( 'clientEvents' , "schedule-<%= @schedule.id.to_s %>" );
   var event = c[0];
   event.title = "<%= @schedule.notes.to_s %>";
   event.start =  "<%= @schedule.schedule_start.iso8601 %>";
   event.end = "<%= @schedule.schedule_end.iso8601 %>";
   $('#calendar').fullCalendar('updateEvent', event);


<%else%>
  $("#new-object").html("<%= escape_javascript(render :partial => '/schedules/form' )%>").dialog({ zIndex: 3000, width: "70%", title: 'New Schedule', modal: true, resizable: false });
  schedule_date_picker();
<%end%>