config/routes.rb
Uklocumdoctors::Application.routes.draw do

  devise_for :users

   namespace :admin do
     root :to => 'doctors#index'
     resources :staffs
     resources :doctors 
     resources :users
   end

  resources :doctors
  resources :nurse_practitioners
  resources :users do
    resources :locations
    resources :schedules do
      collection do
        get 'get_schedules'
      end
    end
  end

   root :to => 'dashboard#index'
  
  get "settingstandards" => "dashboard#settingstandards"
  get "generalpractitioners" => "dashboard#generalpractitioners"
  get "doctorinfo" => "dashboard#doctorinfo"
  get "nursesinfo" => "dashboard#nursesinfo"
  get "aboutus" => "dashboard#aboutus"
  match "contactus" => "dashboard#contactus" , via: [:post, :get]
  get "register" => "dashboard#register"
  get "contactonline" => "dashboard#contactonline"

  # match ':controller(/:action(/:id))(.:format)'
end

app/views/shared/_admin_navigation.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      .pull-left
        .pull-left= link_to image_tag("/assets/locum-logo-small.png"), root_path  
        %ul.nav.pull-left
          %li= link_to "Doctors", admin_doctors_path
          %li= link_to "Nurse practitioner", admin_staffs_path

      
 
      .right
        %ul.nav.main_links
          - if current_user
            %li= link_to "Website", root_path
            %li= link_to "<i class='icon-off icon-white'></i> Log out".html_safe, destroy_user_session_path, :method => :delete, :class => 'logout'
          - else
            %li= link_to "Sign in", new_user_session_path

      .clearfix

app/views/shared/_admin_side_bar.html.haml
%ul.nav.nav-list.bs-docs-sidenav
  %li= link_to '<i class="icon-chevron-right"></i>Doctors'.html_safe, admin_doctors_path
  %li= link_to '<i class="icon-chevron-right"></i> Nurse practitioner'.html_safe, admin_staffs_path
  

app/views/shared/_alert.html.haml
.alert_div
  - unless notice.blank?
    .alert.alert-success 
      = notice 
  - unless alert.blank?
    %p.alert= alert

app/views/shared/_navigation.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to image_tag("/assets/locum-logo-small.png"), root_path
      .right
        %ul.nav.main_links
          - if current_user
            -if current_user.doctor? || current_user.staff?
              %li= link_to "Locations", "#" 
            %li= link_to "<i class='icon-off icon-white'></i> Log out".html_safe, destroy_user_session_path, :method => :delete, :class => 'logout'
          - else
            %li= link_to "Register as doctor", new_doctor_path, :remote => true
            %li= link_to "Register as nurse practitioner", new_nurse_practitioner_path, :remote => true
            %li= link_to "Sign in", new_user_session_path

        #new-object

app/views/shared/_practitioner_navigation.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to image_tag("/assets/locum-logo-small.png"), root_path
      .right
        %ul.nav.main_links
          - if current_user
            %li= link_to "Website", root_path
            -if current_user.admin?
              %li= link_to "Admin", admin_root_path

            - if current_user.doctor_or_staff?
              - if current_user.doctor?
                %li= link_to "Edit Profile", edit_doctor_path(current_user) ,:remote => true
              -else
                %li= link_to "Edit Profile", edit_nurse_practitioner_path(current_user), :remote => true

            -if current_user.admin? || current_user.doctor_or_staff?
              %li= link_to "Schedules", user_schedules_path(@user)
              %li= link_to "Locations", user_locations_path(@user)
            %li= link_to "<i class='icon-off icon-white'></i> Log out".html_safe, destroy_user_session_path, :method => :delete, :class => 'logout'
          - else
            %li= link_to "Sign in", new_user_session_path

#edit-form