config/routes.rb
Uklocumdoctors::Application.routes.draw do

  devise_for :users

   namespace :admin do
     root :to => 'doctors#index'
     resources :staffs
     resources :doctors 
     resources :users
   end

  resources :doctors
  resources :nurse_practitioners
  resources :users do
    resources :locations
    resources :schedules do
      collection do
        get 'get_schedules'
      end
    end
  end

   root :to => 'dashboard#index'
  
  get "settingstandards" => "dashboard#settingstandards"
  get "generalpractitioners" => "dashboard#generalpractitioners"
  get "doctorinfo" => "dashboard#doctorinfo"
  get "nursesinfo" => "dashboard#nursesinfo"
  get "aboutus" => "dashboard#aboutus"
  match "contactus" => "dashboard#contactus" , via: [:post, :get]
  get "register" => "dashboard#register"
  get "contactonline" => "dashboard#contactonline"

  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/admin/staffs_controller.rb
class Admin::StaffsController < Admin::BaseController

  def index
  	@search = User.staffs.includes([:profile]).search(params[:search])
    @staffs = @search.paginate(:page => params[:page], :per_page => 10)
  end


  def new
  	@staff = User.new()
  	@staff.build_profile
  	#@staff.build_staff_default_doctor_selection 
  end

  def create
  	@staff = User.new(params[:user])
  	if @staff.save
  	  @staff.roles << Role.find_by_name("nurse")
  	end
  end

  def edit
  	@staff = User.find(params[:id])
  	#@staff.build_staff_default_doctor_selection if @staff.staff_default_doctor_selection.blank?
  end

  def show
    @staff = User.find(params[:id])
  end  

  def update
  	@staff = User.find(params[:id])
  	remove_password_from_params_if_blank 
  	@staff.update_attributes(params[:user])
  end

  def destroy
    @doctor = User.find(params[:id])
    @doctor.destroy
    redirect_to admin_staffs_path
  end  
end

app/views/admin/staffs/_edit_form.html.haml
= simple_form_for(@staff, :url => admin_staff_path(@staff),  :remote => true) do |f|
  = render "/admin/doctors/fields", { :f => f }
  = f.button :submit, "Update Staff", :class => 'save-btn', :disable_with => 'Saving...'

app/views/admin/staffs/_form.html.haml
= simple_form_for(@staff, :url => admin_staffs_path,  :remote => true) do |f|
  = render "/admin/doctors/fields", { :f => f }
  = f.button :submit, "Create Staff", :class => 'save-btn', :disable_with => 'Saving...'

app/views/admin/staffs/create.js.erb
<% if @staff.errors.blank? %>
   window.location.href = window.location.href;
<%else%>
  $('#staff').html("<%= escape_javascript(render :partial => '/admin/staffs/form' )%>");
<%end%>

app/views/admin/staffs/edit.js.erb
$('#staff').html("<%= escape_javascript(render :partial => '/admin/staffs/edit_form' )%>").dialog({ zIndex: 3000, width: "70%", title: 'Edit - <%= @staff.name %>', modal: true , resizable: false});
 

app/views/admin/staffs/index.html.haml
%ul.breadcrumb
  %li.title 
    Listing nurse practitioners
  %li.active.right nurse practitioners
  %li.right
    Admin
    = divider 

= form_for(@search, :url => admin_staffs_path, :html => { :class => 'form-search' }) do |f|
  %table.table.table-bordered 
    %tbody
      %tr
        %td= f.text_field :name_contains, :placeholder => "Name contains"

        %td= f.text_field :profile_mobile_contains, :placeholder => "Mobile"
        %td
          = f.submit "search", :class => 'btn'
          = link_to new_text('staff'), new_admin_staff_path, :remote => true , :class => 'btn btn-primary'




%table.table.table-bordered
  %thead
    %tr
      %th Name
      %th Email
      %th mobile
      %th Address
      %th
  %tbody
    - @staffs.each do |staff|
      %tr 
        %td= staff.name
        %td= staff.email
        %td= staff.profile.mobile
        %td= staff.profile.address

        %td
          = link_to "Details", admin_staff_path(staff), :class => 'btn btn-mini'
          = link_to edit_text(), edit_admin_staff_path(staff), :class => 'btn btn-mini', :remote => true
          = link_to "Schedules", user_schedules_path(staff), :class => 'btn btn-info btn-mini'
          = link_to "Locations", user_locations_path(staff), :class => 'btn btn-info btn-mini'
          = link_to "Delete", admin_staff_path(staff), :method => :delete, :confirm => "Are you sure? ", :class => 'btn btn-danger btn-mini'

= will_paginate(@staffs)        
#staff

app/views/admin/staffs/new.js.erb
$('#staff').html("<%= escape_javascript(render :partial => '/admin/staffs/form' )%>").dialog({ zIndex: 3000, width: "70%", title: 'New Staff', modal: true , resizable: false});

app/views/admin/staffs/show.html.haml
%ul.breadcrumb
  %li.title 
    = @staff.name
  %li.active.right= @staff.name  
  %li.right
    staffs
    = divider   
  %li.right
    Admin
    = divider

.pull-left
  %h2 Details
.pull-right
  = link_to edit_text(), edit_admin_staff_path(@staff), :class => 'btn btn-info', :remote => true  
  = link_to "staff Lists", admin_staffs_path, :class => 'btn'

.clearfix    

%table.table.table-bordered
  
  %tr
    %th Name
    %td= @staff.name
  %tr
    %th Email
    %td= @staff.email
  %tr
    %th UserName
    %td= @staff.username
  %tr
    %th speciality
    %td=@staff.profile.speciality rescue ""
  %tr
    %th qualification
    %td=@staff.profile.qualification rescue ""
  %tr
    %th Organisation
    %td=@staff.profile.organisation rescue ""
  %tr
    %th Telephone day 
    %td=@staff.profile.telephone_day  rescue ""
  %tr
    %th Telephone night
    %td= @staff.profile.telephone_night  rescue ""
  %tr
    %th Mobile
    %td= @staff.profile.mobile rescue ""
  %tr
    %th Fax
    %td=@staff.profile.fax rescue ""

  %tr
    %th Address
    %td=@staff.profile.address rescue ""
  %tr
    %th Other information
    %td=@staff.profile.other_information  rescue ""

#staff

app/views/admin/staffs/update.js.erb
<% if @staff.errors.blank? %>
   window.location.href = window.location.href;  
<%else%>
  $('#staff').html("<%= escape_javascript(render :partial => '/admin/staffs/edit_form' )%>");
<%end%>